import { db } from '../src/db';
import { properties } from '../src/db/schema';

const now = new Date().toISOString();

const locationProperties = [
  { title: 'Bournemouth Beach House', slug: 'bournemouth-beach-house', location: 'Bournemouth, Dorset', region: 'South England', sleepsMin: 10, sleepsMax: 14, bedrooms: 7, bathrooms: 4, priceFromMidweek: 85, priceFromWeekend: 99, description: 'Stunning beachside property in Bournemouth with panoramic sea views, hot tub, and direct beach access. Perfect for group getaways.', heroImage: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1600&q=90' },
  { title: 'Brighton Seaside Villa', slug: 'brighton-seaside-villa', location: 'Brighton, East Sussex', region: 'South England', sleepsMin: 12, sleepsMax: 16, bedrooms: 8, bathrooms: 5, priceFromMidweek: 95, priceFromWeekend: 115, description: 'Elegant Victorian villa near Brighton Pier with games room, hot tub, and stunning period features. Walking distance to nightlife.', heroImage: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1600&q=90' },
  { title: 'Bristol Harbourside Loft', slug: 'bristol-harbourside-loft', location: 'Bristol, Avon', region: 'South West England', sleepsMin: 8, sleepsMax: 12, bedrooms: 6, bathrooms: 3, priceFromMidweek: 79, priceFromWeekend: 95, description: 'Modern converted warehouse loft in Bristol\'s vibrant harbour area. Open-plan living, rooftop terrace, and city views.', heroImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=90' },
  { title: 'Cambridge College House', slug: 'cambridge-college-house', location: 'Cambridge, Cambridgeshire', region: 'East England', sleepsMin: 10, sleepsMax: 14, bedrooms: 7, bathrooms: 4, priceFromMidweek: 89, priceFromWeekend: 105, description: 'Charming Georgian townhouse in historic Cambridge. Garden, hot tub, and walking distance to colleges and punting.', heroImage: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1600&q=90' },
  { title: 'Canterbury Cathedral View', slug: 'canterbury-cathedral-view', location: 'Canterbury, Kent', region: 'South East England', sleepsMin: 8, sleepsMax: 12, bedrooms: 6, bathrooms: 3, priceFromMidweek: 75, priceFromWeekend: 89, description: 'Historic property with stunning cathedral views in the heart of Canterbury. Period features meet modern comfort.', heroImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=90' },
  { title: 'Cardiff Bay Penthouse', slug: 'cardiff-bay-penthouse', location: 'Cardiff, Wales', region: 'Wales', sleepsMin: 10, sleepsMax: 14, bedrooms: 7, bathrooms: 4, priceFromMidweek: 82, priceFromWeekend: 98, description: 'Luxury penthouse overlooking Cardiff Bay with private terrace, hot tub, and panoramic views. Steps from restaurants and bars.', heroImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1600&q=90' },
  { title: 'Cheltenham Regency Manor', slug: 'cheltenham-regency-manor', location: 'Cheltenham, Gloucestershire', region: 'South West England', sleepsMin: 14, sleepsMax: 20, bedrooms: 10, bathrooms: 6, priceFromMidweek: 110, priceFromWeekend: 135, description: 'Elegant Regency manor house in the heart of Cheltenham. Perfect for racing weekends with spa facilities and games room.', heroImage: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1600&q=90' },
  { title: 'Chester Tudor House', slug: 'chester-tudor-house', location: 'Chester, Cheshire', region: 'North West England', sleepsMin: 10, sleepsMax: 14, bedrooms: 7, bathrooms: 4, priceFromMidweek: 85, priceFromWeekend: 99, description: 'Beautiful Tudor-style property near Chester\'s famous Rows. Hot tub, garden, and period features throughout.', heroImage: 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=1600&q=90' },
  { title: 'Cornwall Coastal Retreat', slug: 'cornwall-coastal-retreat', location: 'Newquay, Cornwall', region: 'South West England', sleepsMin: 12, sleepsMax: 16, bedrooms: 8, bathrooms: 5, priceFromMidweek: 95, priceFromWeekend: 115, description: 'Spectacular clifftop property with ocean views and direct beach access. Hot tub, surfboard storage, and BBQ area.', heroImage: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1600&q=90' },
  { title: 'Cotswolds Manor House', slug: 'cotswolds-manor-house', location: 'Chipping Campden, Cotswolds', region: 'South West England', sleepsMin: 16, sleepsMax: 22, bedrooms: 11, bathrooms: 7, priceFromMidweek: 125, priceFromWeekend: 150, description: 'Stunning honey-stone manor in the heart of the Cotswolds. Swimming pool, tennis court, and acres of gardens.', heroImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600&q=90' },
  { title: 'Devon Country Estate', slug: 'devon-country-estate', location: 'Exeter, Devon', region: 'South West England', sleepsMin: 14, sleepsMax: 18, bedrooms: 9, bathrooms: 5, priceFromMidweek: 105, priceFromWeekend: 125, description: 'Magnificent country estate in rural Devon with indoor pool, hot tub, and stunning countryside views.', heroImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1600&q=90' },
  { title: 'Durham Castle Lodge', slug: 'durham-castle-lodge', location: 'Durham, County Durham', region: 'North East England', sleepsMin: 10, sleepsMax: 14, bedrooms: 7, bathrooms: 4, priceFromMidweek: 82, priceFromWeekend: 98, description: 'Historic lodge near Durham Cathedral with stunning views, hot tub, and traditional British charm.', heroImage: 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=1600&q=90' },
  { title: 'Exeter Georgian Townhouse', slug: 'exeter-georgian-townhouse', location: 'Exeter, Devon', region: 'South West England', sleepsMin: 8, sleepsMax: 12, bedrooms: 6, bathrooms: 4, priceFromMidweek: 79, priceFromWeekend: 95, description: 'Elegant Georgian townhouse in Exeter city centre. Period features, courtyard garden, and walking distance to cathedral.', heroImage: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1600&q=90' },
  { title: 'Harrogate Spa House', slug: 'harrogate-spa-house', location: 'Harrogate, North Yorkshire', region: 'North England', sleepsMin: 12, sleepsMax: 16, bedrooms: 8, bathrooms: 5, priceFromMidweek: 95, priceFromWeekend: 115, description: 'Luxurious Victorian property in the spa town of Harrogate. Private spa facilities, hot tub, and beautiful gardens.', heroImage: 'https://images.unsplash.com/photo-1600047508788-786f3865b4b9?w=1600&q=90' },
  { title: 'Lake District Lodge', slug: 'lake-district-lodge', location: 'Windermere, Lake District', region: 'North West England', sleepsMin: 14, sleepsMax: 18, bedrooms: 9, bathrooms: 6, priceFromMidweek: 115, priceFromWeekend: 140, description: 'Spectacular lakeside lodge with private jetty, hot tub, and mountain views. Perfect for outdoor adventures.', heroImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=90' },
  { title: 'Leeds City Warehouse', slug: 'leeds-city-warehouse', location: 'Leeds, West Yorkshire', region: 'North England', sleepsMin: 10, sleepsMax: 14, bedrooms: 7, bathrooms: 4, priceFromMidweek: 79, priceFromWeekend: 95, description: 'Stylish converted warehouse in Leeds city centre. Industrial chic design, rooftop terrace, and close to nightlife.', heroImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=90' },
  { title: 'Liverpool Dockside Loft', slug: 'liverpool-dockside-loft', location: 'Liverpool, Merseyside', region: 'North West England', sleepsMin: 12, sleepsMax: 16, bedrooms: 8, bathrooms: 5, priceFromMidweek: 85, priceFromWeekend: 99, description: 'Stunning waterfront property at Liverpool\'s Albert Dock. Modern design, city views, and steps from Beatles attractions.', heroImage: 'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=1600&q=90' },
  { title: 'London Townhouse', slug: 'london-townhouse', location: 'London, Greater London', region: 'South East England', sleepsMin: 10, sleepsMax: 14, bedrooms: 7, bathrooms: 5, priceFromMidweek: 150, priceFromWeekend: 185, description: 'Elegant Georgian townhouse in central London. Private garden, modern amenities, and close to West End theatres.', heroImage: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1600&q=90' },
  { title: 'Manchester Penthouse', slug: 'manchester-penthouse', location: 'Manchester, Greater Manchester', region: 'North West England', sleepsMin: 10, sleepsMax: 14, bedrooms: 7, bathrooms: 4, priceFromMidweek: 85, priceFromWeekend: 99, description: 'Luxury city centre penthouse with skyline views, private terrace, and walking distance to Northern Quarter.', heroImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=90' },
  { title: 'Margate Seaside Escape', slug: 'margate-seaside-escape', location: 'Margate, Kent', region: 'South East England', sleepsMin: 8, sleepsMax: 12, bedrooms: 6, bathrooms: 3, priceFromMidweek: 72, priceFromWeekend: 85, description: 'Charming coastal property near Margate\'s sandy beach. Retro-chic interiors, sea views, and close to Turner Contemporary.', heroImage: 'https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=1600&q=90' },
  { title: 'Newcastle Quayside House', slug: 'newcastle-quayside-house', location: 'Newcastle upon Tyne, Tyne and Wear', region: 'North East England', sleepsMin: 12, sleepsMax: 16, bedrooms: 8, bathrooms: 5, priceFromMidweek: 82, priceFromWeekend: 98, description: 'Modern riverside property on Newcastle\'s famous Quayside. Hot tub, games room, and nightlife on your doorstep.', heroImage: 'https://images.unsplash.com/photo-1600566752447-f4e219736894?w=1600&q=90' },
  { title: 'Newquay Surf Lodge', slug: 'newquay-surf-lodge', location: 'Newquay, Cornwall', region: 'South West England', sleepsMin: 10, sleepsMax: 14, bedrooms: 7, bathrooms: 4, priceFromMidweek: 85, priceFromWeekend: 99, description: 'Ultimate surf retreat near Fistral Beach. Hot tub, surfboard storage, and stunning ocean views.', heroImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1600&q=90' },
  { title: 'Norfolk Broads Retreat', slug: 'norfolk-broads-retreat', location: 'Norwich, Norfolk', region: 'East England', sleepsMin: 12, sleepsMax: 16, bedrooms: 8, bathrooms: 5, priceFromMidweek: 89, priceFromWeekend: 105, description: 'Waterside property in the Norfolk Broads. Private mooring, hot tub, and peaceful countryside setting.', heroImage: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1600&q=90' },
  { title: 'Nottingham Forest Lodge', slug: 'nottingham-forest-lodge', location: 'Nottingham, Nottinghamshire', region: 'East Midlands', sleepsMin: 10, sleepsMax: 14, bedrooms: 7, bathrooms: 4, priceFromMidweek: 79, priceFromWeekend: 95, description: 'Charming lodge near Sherwood Forest. Hot tub, games room, and easy access to Nottingham city centre.', heroImage: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1600&q=90' },
  { title: 'Oxford College Manor', slug: 'oxford-college-manor', location: 'Oxford, Oxfordshire', region: 'South East England', sleepsMin: 14, sleepsMax: 18, bedrooms: 9, bathrooms: 5, priceFromMidweek: 105, priceFromWeekend: 125, description: 'Stunning manor house near Oxford\'s dreaming spires. Indoor pool, hot tub, and beautiful gardens.', heroImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=90' },
  { title: 'Peak District Farmhouse', slug: 'peak-district-farmhouse', location: 'Bakewell, Peak District', region: 'East Midlands', sleepsMin: 16, sleepsMax: 20, bedrooms: 10, bathrooms: 6, priceFromMidweek: 110, priceFromWeekend: 135, description: 'Traditional Peak District farmhouse with modern luxury. Hot tub, games barn, and stunning valley views.', heroImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600&q=90' },
  { title: 'Plymouth Harbour House', slug: 'plymouth-harbour-house', location: 'Plymouth, Devon', region: 'South West England', sleepsMin: 10, sleepsMax: 14, bedrooms: 7, bathrooms: 4, priceFromMidweek: 79, priceFromWeekend: 95, description: 'Historic harbour-side property with stunning sea views. Hot tub, BBQ terrace, and close to the Barbican.', heroImage: 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=1600&q=90' },
  { title: 'Sheffield Steel Works', slug: 'sheffield-steel-works', location: 'Sheffield, South Yorkshire', region: 'North England', sleepsMin: 10, sleepsMax: 14, bedrooms: 7, bathrooms: 4, priceFromMidweek: 75, priceFromWeekend: 89, description: 'Converted steel works with industrial-chic design. Rooftop hot tub, games room, and close to Peak District.', heroImage: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1600&q=90' },
  { title: 'St Ives Artists Retreat', slug: 'st-ives-artists-retreat', location: 'St Ives, Cornwall', region: 'South West England', sleepsMin: 8, sleepsMax: 12, bedrooms: 6, bathrooms: 4, priceFromMidweek: 89, priceFromWeekend: 105, description: 'Light-filled coastal property in artistic St Ives. Sea views, private terrace, and steps from Tate gallery.', heroImage: 'https://images.unsplash.com/photo-1600047508788-786f3865b4b9?w=1600&q=90' },
  { title: 'Stratford Shakespeare House', slug: 'stratford-shakespeare-house', location: 'Stratford-upon-Avon, Warwickshire', region: 'West Midlands', sleepsMin: 12, sleepsMax: 16, bedrooms: 8, bathrooms: 5, priceFromMidweek: 95, priceFromWeekend: 115, description: 'Tudor-style property in Shakespeare\'s birthplace. Hot tub, garden, and walking distance to RSC theatre.', heroImage: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1600&q=90' },
  { title: 'Suffolk Coastal Cottage', slug: 'suffolk-coastal-cottage', location: 'Southwold, Suffolk', region: 'East England', sleepsMin: 10, sleepsMax: 14, bedrooms: 7, bathrooms: 4, priceFromMidweek: 85, priceFromWeekend: 99, description: 'Charming coastal property near Southwold beach. Hot tub, garden, and close to the famous pier.', heroImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1600&q=90' },
  { title: 'Sussex Downs Manor', slug: 'sussex-downs-manor', location: 'Lewes, East Sussex', region: 'South East England', sleepsMin: 14, sleepsMax: 18, bedrooms: 9, bathrooms: 6, priceFromMidweek: 105, priceFromWeekend: 125, description: 'Elegant manor house in the South Downs. Indoor pool, tennis court, and stunning countryside views.', heroImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600&q=90' },
  { title: 'Windsor Royal Residence', slug: 'windsor-royal-residence', location: 'Windsor, Berkshire', region: 'South East England', sleepsMin: 12, sleepsMax: 16, bedrooms: 8, bathrooms: 5, priceFromMidweek: 115, priceFromWeekend: 140, description: 'Regal property near Windsor Castle. Swimming pool, hot tub, and beautiful landscaped gardens.', heroImage: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1600&q=90' },
  { title: 'York Medieval Manor', slug: 'york-medieval-manor', location: 'York, North Yorkshire', region: 'North England', sleepsMin: 14, sleepsMax: 18, bedrooms: 9, bathrooms: 5, priceFromMidweek: 99, priceFromWeekend: 120, description: 'Historic manor near York Minster. Hot tub, walled garden, and walking distance to the Shambles.', heroImage: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1600&q=90' },
  { title: 'Yorkshire Dales Lodge', slug: 'yorkshire-dales-lodge', location: 'Skipton, North Yorkshire', region: 'North England', sleepsMin: 16, sleepsMax: 20, bedrooms: 10, bathrooms: 6, priceFromMidweek: 110, priceFromWeekend: 135, description: 'Stunning lodge in the Yorkshire Dales with panoramic views, hot tub, and games room. Perfect for outdoor adventures.', heroImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=90' },
];

async function main() {
  console.log('Starting property seeding...');
  
  for (const prop of locationProperties) {
    try {
      await db.insert(properties).values({
        ...prop,
        checkInOut: 'Check-in 4pm, Check-out 10am',
        featured: false,
        isPublished: true,
        status: 'active',
        houseRules: null,
        iCalURL: null,
        heroVideo: null,
        floorplanURL: null,
        mapLat: null,
        mapLng: null,
        ownerContact: null,
        createdAt: now,
        updatedAt: now,
      });
      console.log(`✅ Added: ${prop.title}`);
    } catch (error: any) {
      if (error.message?.includes('UNIQUE constraint')) {
        console.log(`⏭️ Skipped (already exists): ${prop.title}`);
      } else {
        console.error(`❌ Error adding ${prop.title}:`, error.message);
      }
    }
  }
  
  console.log('\n✅ Property seeding completed!');
  process.exit(0);
}

main().catch((error) => {
  console.error('❌ Seeder failed:', error);
  process.exit(1);
});
