import { db } from '@/db';
import { bookings } from '@/db/schema';

async function main() {
    const sampleBookings = [
        {
            propertyName: 'Brighton Manor',
            propertyLocation: 'Brighton, East Sussex',
            guestName: 'Sophie Anderson',
            guestEmail: 'sophie.anderson@gmail.com',
            guestPhone: '+44 7789 123456',
            checkInDate: '2025-02-14',
            checkOutDate: '2025-02-16',
            numberOfGuests: 14,
            occasion: 'hen party',
            bookingStatus: 'confirmed',
            totalPrice: 3500.00,
            depositAmount: 875.00,
            depositPaid: true,
            balanceAmount: 2625.00,
            balancePaid: false,
            specialRequests: 'Early check-in required',
            experiencesSelected: ['Cocktail Masterclass', 'Private Chef', 'Spa Treatments'],
            adminNotes: 'VIP customer - previous booking went well',
            createdAt: '2024-11-20T10:30:00.000Z',
            updatedAt: '2024-12-01T14:22:00.000Z',
        },
        {
            propertyName: 'Bath Spa Retreat',
            propertyLocation: 'Bath, Somerset',
            guestName: 'Emma Thompson',
            guestEmail: 'emma.thompson@hotmail.co.uk',
            guestPhone: '+44 7892 456789',
            checkInDate: '2025-03-07',
            checkOutDate: '2025-03-09',
            numberOfGuests: 16,
            occasion: 'hen party',
            bookingStatus: 'confirmed',
            totalPrice: 4200.00,
            depositAmount: 1050.00,
            depositPaid: true,
            balanceAmount: 3150.00,
            balancePaid: true,
            specialRequests: 'Dietary requirements: 2 vegetarians, 1 vegan',
            experiencesSelected: ['Spa Treatments', 'Private Chef', 'Bottomless Brunch', 'Life Drawing'],
            adminNotes: 'Called to confirm arrival time',
            createdAt: '2024-12-05T09:15:00.000Z',
            updatedAt: '2024-12-20T16:45:00.000Z',
        },
        {
            propertyName: 'Manchester Party House',
            propertyLocation: 'Manchester, Greater Manchester',
            guestName: 'Charlotte Williams',
            guestEmail: 'charlotte.w@outlook.com',
            guestPhone: '+44 7654 321098',
            checkInDate: '2025-01-24',
            checkOutDate: '2025-01-26',
            numberOfGuests: 12,
            occasion: 'hen party',
            bookingStatus: 'confirmed',
            totalPrice: 2800.00,
            depositAmount: 700.00,
            depositPaid: true,
            balanceAmount: 2100.00,
            balancePaid: false,
            specialRequests: 'Celebrating bride\'s 30th birthday too',
            experiencesSelected: ['Cocktail Masterclass', 'Butlers in the Buff'],
            adminNotes: null,
            createdAt: '2024-10-18T14:20:00.000Z',
            updatedAt: '2024-11-02T11:30:00.000Z',
        },
        {
            propertyName: 'Bournemouth Beach House',
            propertyLocation: 'Bournemouth, Dorset',
            guestName: 'Lucy Davies',
            guestEmail: 'lucy.davies@gmail.com',
            guestPhone: '+44 7456 789012',
            checkInDate: '2025-03-21',
            checkOutDate: '2025-03-23',
            numberOfGuests: 18,
            occasion: 'hen party',
            bookingStatus: 'confirmed',
            totalPrice: 4800.00,
            depositAmount: 1200.00,
            depositPaid: true,
            balanceAmount: 3600.00,
            balancePaid: true,
            specialRequests: null,
            experiencesSelected: ['Private Chef', 'Bottomless Brunch', 'Spa Treatments'],
            adminNotes: 'Requested late checkout - approved',
            createdAt: '2024-11-30T08:45:00.000Z',
            updatedAt: '2025-01-05T10:15:00.000Z',
        },
        {
            propertyName: 'Newcastle Quayside Residence',
            propertyLocation: 'Newcastle, Tyne and Wear',
            guestName: 'Jessica Brown',
            guestEmail: 'jess.brown@hotmail.co.uk',
            guestPhone: '+44 7321 654987',
            checkInDate: '2025-02-08',
            checkOutDate: '2025-02-10',
            numberOfGuests: 10,
            occasion: 'hen party',
            bookingStatus: 'pending',
            totalPrice: 2500.00,
            depositAmount: 625.00,
            depositPaid: false,
            balanceAmount: 1875.00,
            balancePaid: false,
            specialRequests: 'Need extra parking spaces',
            experiencesSelected: ['Cocktail Masterclass', 'Life Drawing'],
            adminNotes: null,
            createdAt: '2025-01-08T12:00:00.000Z',
            updatedAt: '2025-01-08T12:00:00.000Z',
        },
        {
            propertyName: 'Brighton Manor',
            propertyLocation: 'Brighton, East Sussex',
            guestName: 'Olivia Taylor',
            guestEmail: 'olivia.taylor@outlook.com',
            guestPhone: '+44 7567 890123',
            checkInDate: '2025-03-14',
            checkOutDate: '2025-03-16',
            numberOfGuests: 15,
            occasion: 'hen party',
            bookingStatus: 'pending',
            totalPrice: 3800.00,
            depositAmount: 950.00,
            depositPaid: false,
            balanceAmount: 2850.00,
            balancePaid: false,
            specialRequests: null,
            experiencesSelected: ['Butlers in the Buff', 'Private Chef', 'Cocktail Masterclass'],
            adminNotes: null,
            createdAt: '2025-01-10T15:30:00.000Z',
            updatedAt: '2025-01-10T15:30:00.000Z',
        },
        {
            propertyName: 'Bath Spa Retreat',
            propertyLocation: 'Bath, Somerset',
            guestName: 'Hannah Wilson',
            guestEmail: 'hannah.wilson@gmail.com',
            guestPhone: '+44 7890 234567',
            checkInDate: '2025-04-11',
            checkOutDate: '2025-04-13',
            numberOfGuests: 13,
            occasion: 'hen party',
            bookingStatus: 'pending',
            totalPrice: 3300.00,
            depositAmount: 825.00,
            depositPaid: false,
            balanceAmount: 2475.00,
            balancePaid: false,
            specialRequests: 'Gluten-free options needed',
            experiencesSelected: ['Spa Treatments', 'Bottomless Brunch'],
            adminNotes: null,
            createdAt: '2025-01-12T09:45:00.000Z',
            updatedAt: '2025-01-12T09:45:00.000Z',
        },
        {
            propertyName: 'Manchester Party House',
            propertyLocation: 'Manchester, Greater Manchester',
            guestName: 'Grace Mitchell',
            guestEmail: 'grace.mitchell@hotmail.co.uk',
            guestPhone: '+44 7234 567890',
            checkInDate: '2024-11-15',
            checkOutDate: '2024-11-17',
            numberOfGuests: 14,
            occasion: 'hen party',
            bookingStatus: 'completed',
            totalPrice: 3200.00,
            depositAmount: 800.00,
            depositPaid: true,
            balanceAmount: 2400.00,
            balancePaid: true,
            specialRequests: null,
            experiencesSelected: ['Cocktail Masterclass', 'Butlers in the Buff', 'Private Chef'],
            adminNotes: null,
            createdAt: '2024-09-20T11:00:00.000Z',
            updatedAt: '2024-11-18T10:00:00.000Z',
        },
        {
            propertyName: 'Bournemouth Beach House',
            propertyLocation: 'Bournemouth, Dorset',
            guestName: 'Amelia Roberts',
            guestEmail: 'amelia.roberts@outlook.com',
            guestPhone: '+44 7678 901234',
            checkInDate: '2024-12-06',
            checkOutDate: '2024-12-08',
            numberOfGuests: 17,
            occasion: 'hen party',
            bookingStatus: 'completed',
            totalPrice: 4500.00,
            depositAmount: 1125.00,
            depositPaid: true,
            balanceAmount: 3375.00,
            balancePaid: true,
            specialRequests: null,
            experiencesSelected: ['Private Chef', 'Life Drawing', 'Spa Treatments', 'Bottomless Brunch'],
            adminNotes: null,
            createdAt: '2024-10-01T13:30:00.000Z',
            updatedAt: '2024-12-09T09:15:00.000Z',
        },
        {
            propertyName: 'Newcastle Quayside Residence',
            propertyLocation: 'Newcastle, Tyne and Wear',
            guestName: 'Isabella Moore',
            guestEmail: 'isabella.m@gmail.com',
            guestPhone: '+44 7345 678901',
            checkInDate: '2025-02-28',
            checkOutDate: '2025-03-02',
            numberOfGuests: 11,
            occasion: 'hen party',
            bookingStatus: 'cancelled',
            totalPrice: 2700.00,
            depositAmount: 675.00,
            depositPaid: true,
            balanceAmount: 2025.00,
            balancePaid: false,
            specialRequests: null,
            experiencesSelected: ['Cocktail Masterclass'],
            adminNotes: null,
            createdAt: '2024-12-10T16:20:00.000Z',
            updatedAt: '2025-01-05T14:30:00.000Z',
        },
    ];

    await db.insert(bookings).values(sampleBookings);
    
    console.log('✅ Bookings seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});