import { db } from '@/db';
import { experiences } from '@/db/schema';

async function main() {
    await db.delete(experiences);
    
    const currentTimestamp = new Date().toISOString();
    
    const sampleExperiences = [
        {
            title: 'Private Chef Experience',
            slug: 'private-chef',
            duration: '3-4 hours',
            groupSizeMin: 8,
            groupSizeMax: 24,
            priceFrom: 65,
            category: 'Food & Drink',
            heroImage: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/8330e9be-5e47-4f2b-bda0-4162d899b6d9/generated_images/professional-stock-photo-of-a-private-ch-e336a153-20251018105040.jpg',
            description: 'Treat your group to a restaurant-quality dining experience in the comfort of your own property. Our professional chefs will create a bespoke menu, prepare everything on-site, and even handle the cleanup – leaving you to relax and enjoy.',
            included: ['Professional private chef for the evening', 'Three-course gourmet meal tailored to your group', 'All ingredients, equipment, and serving ware', 'Menu planning consultation beforehand', 'Full table service and presentation', 'Kitchen cleanup and washing up'],
            whatToProvide: ['Dining space and table setup', 'Basic kitchen facilities (oven, hob, fridge)', 'Crockery and cutlery for your group size', 'Let us know about any dietary requirements in advance'],
            isPublished: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            title: 'Cocktail Masterclass',
            slug: 'cocktail-masterclass',
            duration: '2 hours',
            groupSizeMin: 8,
            groupSizeMax: 20,
            priceFrom: 50,
            category: 'Food & Drink',
            heroImage: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/document-uploads/hen-party-cocktail-classes-4-e1657801576427.jpg-1760963913852.webp',
            description: 'Shake things up with a professional cocktail masterclass in your own property. Learn to make three delicious cocktails, discover bartending secrets, and enjoy the party atmosphere with expert guidance.',
            included: ['Professional mixologist instructor', 'All spirits, mixers, and ingredients for 3 cocktails per person', 'Bar equipment and glassware', 'Recipe cards to take home', 'Cocktail-making techniques and tips', 'Fun group atmosphere with music'],
            whatToProvide: ['Kitchen or bar area with counter space', 'Ice and a freezer', 'Glasses if you prefer to use your own', 'Designated drivers or transport arrangements'],
            isPublished: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            title: 'Sip & Paint',
            slug: 'sip-and-paint',
            duration: '2-3 hours',
            groupSizeMin: 8,
            groupSizeMax: 20,
            priceFrom: 45,
            category: 'Activities',
            heroImage: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/8330e9be-5e47-4f2b-bda0-4162d899b6d9/generated_images/professional-stock-photograph-of-a-sip-a-b0921423-20251024095025.jpg',
            description: 'Unleash your inner artist with a relaxed and fun painting session. No experience needed – our instructor will guide you step-by-step to create your own masterpiece while you sip prosecco and enjoy great company.',
            included: ['Professional art instructor', 'Canvas for each guest', 'All paints, brushes, and art supplies', 'Aprons to protect clothing', 'Step-by-step guidance to complete your painting', 'Set-up and clean-up'],
            whatToProvide: ['Table space for painting', 'Good lighting', 'Chairs for all participants', 'Drinks and snacks (we recommend prosecco!)'],
            isPublished: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            title: 'Life Drawing',
            slug: 'life-drawing',
            duration: '1.5-2 hours',
            groupSizeMin: 8,
            groupSizeMax: 20,
            priceFrom: 48,
            category: 'Activities',
            heroImage: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80',
            description: 'Get cheeky and creative with a life drawing class featuring a naked male model. Professional instruction, plenty of laughs, and a unique experience you\'ll never forget. All skill levels welcome!',
            included: ['Professional art tutor', 'Naked male model', 'Drawing materials for each guest', 'Step-by-step instruction', 'Plenty of laughs', 'Take home your artwork'],
            whatToProvide: ['Table space for drawing', 'Chairs for participants', 'Good lighting', 'Open minds and sense of humour!'],
            isPublished: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            title: 'Butlers in the Buff',
            slug: 'butlers-in-the-buff',
            duration: '2-3 hours',
            groupSizeMin: 8,
            groupSizeMax: 25,
            priceFrom: 60,
            category: 'Entertainment',
            heroImage: 'https://butlersinthebuff.co.uk/wp-content/uploads/2023/05/fun_friendly.jpg.webp',
            description: 'Add some cheeky fun to your celebration with our handsome Butlers in the Buff. These professional hosts will serve drinks and canapés while entertaining your group – guaranteed laughter and memorable photos!',
            included: ['Handsome professional butler', 'Drinks service and hosting', 'Games and entertainment', 'Photo opportunities', 'Canapé service (food not included)', 'Guaranteed fun and laughter'],
            whatToProvide: ['Drinks and canapés to be served', 'Party atmosphere', 'Cameras ready for photos!', 'Age 18+ guests only'],
            isPublished: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            title: 'Spa Treatments',
            slug: 'spa-treatments',
            duration: '2-3 hours',
            groupSizeMin: 8,
            groupSizeMax: 20,
            priceFrom: 75,
            category: 'Beauty & Wellness',
            heroImage: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/8330e9be-5e47-4f2b-bda0-4162d899b6d9/generated_images/professional-stock-photo-of-luxury-spa-t-15d1f1e0-20251021222805.jpg',
            description: 'Treat your group to ultimate relaxation with our mobile spa service. Qualified therapists bring everything needed for massages, facials, manicures, and more – turning your property into a luxury spa retreat.',
            included: ['Qualified mobile spa therapists', 'All treatment products and equipment', 'Massage tables, towels, and robes', 'Relaxing music and aromatherapy', 'Choice of treatments tailored to your group', 'Set-up and clean-up'],
            whatToProvide: ['Quiet space for treatments (bedrooms work perfectly)', 'Access to warm water', 'Comfortable temperature in treatment rooms', 'Let us know treatment preferences in advance'],
            isPublished: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            title: 'Yoga Session',
            slug: 'yoga-session',
            duration: '1.5 hours',
            groupSizeMin: 8,
            groupSizeMax: 20,
            priceFrom: 35,
            category: 'Beauty & Wellness',
            heroImage: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80',
            description: 'Start your celebration with mindful movement and relaxation. Our qualified instructor leads a session suitable for all levels, helping your group unwind and connect before the festivities begin.',
            included: ['Qualified yoga instructor', 'Guided session for all levels', 'Yoga mats for all participants', 'Relaxation and meditation', 'Calming music', 'Post-session herbal tea'],
            whatToProvide: ['Indoor or outdoor space to spread out', 'Quiet environment', 'Comfortable clothing for movement', 'Water bottles for participants'],
            isPublished: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            title: 'Flower Crown Making',
            slug: 'flower-crown-making',
            duration: '1.5-2 hours',
            groupSizeMin: 8,
            groupSizeMax: 20,
            priceFrom: 35,
            category: 'Activities',
            heroImage: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800&q=80',
            description: 'Get creative and make beautiful flower crowns to wear during your celebration. Using fresh flowers and greenery, you\'ll learn floristry techniques and create Instagram-worthy accessories under expert guidance.',
            included: ['Professional florist instructor', 'Fresh flowers and greenery', 'All crafting materials and tools', 'Step-by-step guidance', 'Take-home flower crowns', 'Group photo session with crowns'],
            whatToProvide: ['Table space for crafting', 'Good natural lighting', 'Chairs for participants', 'Enthusiasm and creativity!'],
            isPublished: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            title: 'Hair Styling',
            slug: 'hair-styling',
            duration: '2-3 hours',
            groupSizeMin: 8,
            groupSizeMax: 20,
            priceFrom: 35,
            category: 'Beauty & Wellness',
            heroImage: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80',
            description: 'Get glammed up with professional hair styling in the comfort of your property. Our mobile stylists will create beautiful looks for your group, perfect for a night out or special event.',
            included: ['Professional mobile hair stylist', 'Consultation for each guest', 'Wash, blow-dry, and style', 'Hair products and styling tools', 'Touch-up tips and product recommendations', 'Group discounts for larger parties'],
            whatToProvide: ['Space with mirrors and good lighting', 'Access to plug sockets', 'Hair washed beforehand (or let us know if you\'d like wet hair styling)', 'Any specific style inspiration photos'],
            isPublished: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            title: 'Karaoke Night',
            slug: 'karaoke-night',
            duration: '3-4 hours',
            groupSizeMin: 8,
            groupSizeMax: 30,
            priceFrom: 40,
            category: 'Entertainment',
            heroImage: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80',
            description: 'Bring the party to your property with a full karaoke setup. Professional equipment, thousands of songs, and a host to manage the night – everything you need for an unforgettable sing-along session.',
            included: ['Professional karaoke system with screen', 'Two wireless microphones', 'Sound system and speakers', 'Access to 10,000+ songs across all genres', 'Karaoke host to manage the night', 'Disco lights and party atmosphere'],
            whatToProvide: ['Space for the equipment and performance area', 'TV or projector screen (or we can provide one)', 'Power sockets', 'Your best singing voices and confidence!'],
            isPublished: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        }
    ];

    await db.insert(experiences).values(sampleExperiences);
    
    console.log('✅ Experiences seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});